# Generated by Django 4.2.2 on 2023-11-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentManager',
        ),
    ]
