# Generated by Django 4.2.2 on 2023-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_remove_product_inventory_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('snack', 'Snack')], max_length=255),
        ),
    ]
